
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Vieri.1996


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
  error:
    include-message: always